version: '3.3' # 2버전과 3버전 차이가 많이 남

services:
  my_backend:
    image: asia.gcr.io/holy-moly-341008/my_backend:2.2
    build:
      context: .
      dockerfile: Dockerfile
    # volumes: # 배포 환경 일때는 사용안함
    #   - ./src:/my_backend/src
    env_file:
      - ./.env.prod
    ports:
      - 3000:3000

  # my_database:
  #   platform: linux/x86_64
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'myproject'
  #     MYSQL_ROOT_PASSWORD: '1234'
