export class CashService {

    // 현금체크
    checkValue = () => {
        console.log("현금을 검증합니다");
        // 1. 가진 돈을 검증하는 코드(10줄)
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
    }

}