export class PointService {

    // 포인트 체크
    checkValue = () => {
        console.log("포인트를 검증합니다");
        // 1. 가진 포인트를 검증하는 코드(10줄)
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
    }

}